name: DataCollector

on:
  push:
    paths:
      - 'GoogleCloudFunctions/DataCollector/DataCollector.go'
      - '.github/workflows/datacollector.yml'
  pull_request:
    paths:
      - 'GoogleCloudFunctions/DataCollector/DataCollector.go'
      - '.github/workflows/datacollector.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: disparDataCollector
        runtime: go116
        project_id: ${{ secrets.gcp_project }}
        credentials: ${{ secrets.gcp_credentials }}
#        entry_point: DataCollector
        memory_mb: 128MB
        region: europe-west3
        event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
        event_trigger_resource: projects/${{ secrets.gcp_project }}/topics/links
        source_dir: GoogleCloudFunctions/DataCollector/
        env_vars: DISPARPROJECT=${{ secrets.projectname }}